server:
  port: ${SERVER_PORT:8080}

app:
  frontend-origin: ${APP_FRONTEND_ORIGIN}

spring:
  application:
    name: decker
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_SCHEMA_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  mvc:
    log-request-details: ${LOG_REQUEST_DETAILS:false}

logging:
  level:
    root: ${LOG_LEVEL:INFO}